<?php

namespace Blogger\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends EntityRepository
{
    public function getLatest($limit = null)
    {
        $qb = $this->createQueryBuilder('b')
            ->addOrderBy('b.created', 'DESC');

        if (null !== $limit) {
            $qb->setMaxResults($limit);
        }

        return $qb->getQuery()->getResult();
    }

    public function getOneWithComments($blog_id)
    {
        $qb = $this->createQueryBuilder('b')
            ->select('b,c')
            ->where('b.id = :blog_id')
            ->leftJoin('b.comments', 'c')
            ->addOrderBy('c.created')
            ->setParameter('blog_id', $blog_id);

        return $qb->getQuery()->getSingleResult();
    }
}