<?php

namespace Blogger\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function getLatest($limit = 10)
    {
        $qb = $this->createQueryBuilder('c')
            ->select('c','b')
            ->innerJoin('c.blog','b')
            ->orderBy('c.created', 'desc');

        if (null !== $limit) {
            $qb->setMaxResults($limit);
        }

        return $qb->getQuery()->getResult();
    }
}